/**
 * All WPGraphQL query strings.
 *
 * HOW GRAPHQL WORKS (quick primer):
 * - You describe the shape of the data you want
 * - The server returns exactly that shape — nothing more, nothing less
 * - This is different from REST APIs where you get a fixed response
 *
 * WPGraphQL maps WordPress content types to GraphQL types:
 * - Posts → posts { nodes { ... } }
 * - Custom Post Types → pluralName { nodes { ... } }
 * - ACF fields → grouped under a fieldGroupName
 *
 * The field group names (like `storyFields`) are auto-generated by
 * WPGraphQL for ACF based on your ACF field group name.
 * If your ACF field group is called "Story Fields", the GraphQL
 * field group will be `storyFields`.
 */

// ─── STORIES ────────────────────────────────────────────

/** Get all stories for the listing page */
export const GET_ALL_STORIES = `
  query GetAllStories {
    allStory(first: 50, where: { orderby: { field: DATE, order: DESC } }) {
      nodes {
        title
        slug
        date
        featuredImage {
          node {
            sourceUrl
            altText
          }
        }
        storyFields {
          storyCategory
          storyAuthorName
          storyExcerpt
          storyFeatured
        }
      }
    }
  }
`;

/** Get a single story by its slug (for the detail page) */
export const GET_STORY_BY_SLUG = `
  query GetStoryBySlug($slug: ID!) {
    story(id: $slug, idType: SLUG) {
      title
      slug
      date
      content
      featuredImage {
        node {
          sourceUrl
          altText
        }
      }
      storyFields {
        storyCategory
        storyAuthorName
        storyExcerpt
        storyFeatured
      }
    }
  }
`;

/** Get only the featured story (for homepage) */
export const GET_FEATURED_STORY = `
  query GetFeaturedStory {
    allStory(first: 1, where: { orderby: { field: DATE, order: DESC } }) {
      nodes {
        title
        slug
        date
        featuredImage {
          node {
            sourceUrl
            altText
          }
        }
        storyFields {
          storyCategory
          storyAuthorName
          storyExcerpt
          storyFeatured
        }
      }
    }
  }
`;

/** Get recent stories for homepage (excluding featured) */
export const GET_RECENT_STORIES = `
  query GetRecentStories {
    allStory(first: 3, where: { orderby: { field: DATE, order: DESC } }) {
      nodes {
        title
        slug
        date
        featuredImage {
          node {
            sourceUrl
            altText
          }
        }
        storyFields {
          storyCategory
          storyAuthorName
          storyExcerpt
          storyFeatured
        }
      }
    }
  }
`;

// ─── EVENTS ─────────────────────────────────────────────

/** Get all upcoming events */
export const GET_ALL_EVENTS = `
  query GetAllEvents {
    events(first: 10, where: { orderby: { field: DATE, order: ASC } }) {
      nodes {
        title
        slug
        eventFields {
          eventDate
          eventStartTime
          eventEndTime
          eventLocation
          eventDescription
        }
      }
    }
  }
`;

// ─── RESOURCES ──────────────────────────────────────────

/** Get all resources */
export const GET_ALL_RESOURCES = `
  query GetAllResources {
    resources(first: 50) {
      nodes {
        title
        slug
        resourceFields {
          resourceDescription
          resourceUrl
          resourceCategory
          resourceIcon
        }
      }
    }
  }
`;

// ─── TEAM MEMBERS ───────────────────────────────────────

/** Get all team members for the About page */
export const GET_TEAM_MEMBERS = `
  query GetTeamMembers {
    teamMembers(first: 10) {
      nodes {
        title
        slug
        featuredImage {
          node {
            sourceUrl
            altText
          }
        }
        teamMemberFields {
          memberRole
          memberBio
        }
      }
    }
  }
`;
